# Generated by Django 5.2.15 on 2026-06-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
