# Generated by Django 5.2.15 on 2026-06-30 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('PROPERTY_RECOMMENDATION', 'Property Recommendation'), ('MATCH_SCORE', 'Match Score'), ('LEAD_PRIORITY', 'Lead Priority'), ('LISTING_QUALITY', 'Listing Quality'), ('MARKET_SIGNAL', 'Market Signal')], max_length=40)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='inquiries.inquiry')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insight_type', 'score'], name='ai_insights_insight_ff6cf2_idx'), models.Index(fields=['user', 'insight_type'], name='ai_insights_user_id_5dbcf4_idx'), models.Index(fields=['property', 'insight_type'], name='ai_insights_propert_27afcc_idx')],
            },
        ),
    ]
