from django.urls import path

from apps.admin_panel.views import (
    AdminAgencyDetailView,
    AdminAgencyListView,
    AdminAgencyVerificationView,
    AdminAgentDetailView,
    AdminAgentFeatureView,
    AdminAgentListView,
    AdminAgentVerificationView,
    AdminAppointmentDetailView,
    AdminAppointmentListView,
    AdminAppointmentStatusView,
    AdminDashboardView,
    AdminInquiryDetailView,
    AdminInquiryListView,
    AdminInquiryPriorityView,
    AdminInquiryStatusView,
    AdminNotificationListView,
    AdminNotificationSendView,
    AdminPropertyApprovalView,
    AdminPropertyDetailView,
    AdminPropertyFeatureView,
    AdminPropertyListView,
    AdminPropertyStatusView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserRoleView,
    AdminUserStatusView,
    AuditLogListView,
)


urlpatterns = [
    path("dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("users/<int:pk>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("users/<int:pk>/role/", AdminUserRoleView.as_view(), name="admin-user-role"),
    path("agents/", AdminAgentListView.as_view(), name="admin-agents"),
    path("agents/<int:pk>/", AdminAgentDetailView.as_view(), name="admin-agent-detail"),
    path("agents/<int:pk>/verification/", AdminAgentVerificationView.as_view(), name="admin-agent-verification"),
    path("agents/<int:pk>/feature/", AdminAgentFeatureView.as_view(), name="admin-agent-feature"),
    path("agencies/", AdminAgencyListView.as_view(), name="admin-agencies"),
    path("agencies/<int:pk>/", AdminAgencyDetailView.as_view(), name="admin-agency-detail"),
    path("agencies/<int:pk>/verification/", AdminAgencyVerificationView.as_view(), name="admin-agency-verification"),
    path("properties/", AdminPropertyListView.as_view(), name="admin-properties"),
    path("properties/<int:pk>/", AdminPropertyDetailView.as_view(), name="admin-property-detail"),
    path("properties/<int:pk>/approval/", AdminPropertyApprovalView.as_view(), name="admin-property-approval"),
    path("properties/<int:pk>/feature/", AdminPropertyFeatureView.as_view(), name="admin-property-feature"),
    path("properties/<int:pk>/status/", AdminPropertyStatusView.as_view(), name="admin-property-status"),
    path("inquiries/", AdminInquiryListView.as_view(), name="admin-inquiries"),
    path("inquiries/<int:pk>/", AdminInquiryDetailView.as_view(), name="admin-inquiry-detail"),
    path("inquiries/<int:pk>/status/", AdminInquiryStatusView.as_view(), name="admin-inquiry-status"),
    path("inquiries/<int:pk>/priority/", AdminInquiryPriorityView.as_view(), name="admin-inquiry-priority"),
    path("appointments/", AdminAppointmentListView.as_view(), name="admin-appointments"),
    path("appointments/<int:pk>/", AdminAppointmentDetailView.as_view(), name="admin-appointment-detail"),
    path("appointments/<int:pk>/status/", AdminAppointmentStatusView.as_view(), name="admin-appointment-status"),
    path("notifications/", AdminNotificationListView.as_view(), name="admin-notifications"),
    path("notifications/send/", AdminNotificationSendView.as_view(), name="admin-notification-send"),
    path("audit-logs/", AuditLogListView.as_view(), name="admin-audit-logs"),
]
