# Generated by Django 5.2.15 on 2026-06-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('NEGOTIATION', 'Negotiation'), ('CLOSED', 'Closed'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('PROPERTY_DETAIL', 'Property Detail'), ('CONTACT_FORM', 'Contact Form'), ('AGENT_PROFILE', 'Agent Profile'), ('AI_RECOMMENDATION', 'AI Recommendation')], default='PROPERTY_DETAIL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='agents.agentprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='inquiries_i_status_b9a45f_idx'), models.Index(fields=['source'], name='inquiries_i_source_5a7084_idx')],
            },
        ),
    ]
